# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
subtask:
    - '(subtask|Subtask)'
blocked:
    - '(blocked|Blocked)'
enhancement:
    - '(Idea|Suggestion|Suggested)'
testing:
    - '(in test|In test|In Test|in Test|testing)'
test-success:
    - '(test passed|Test passed)'
bug:
    - '(Bug|bug)'
